### ISSUE TITLE
KeyError: 'Cannot find GCA003697015.1 accession in names.dmp'

### ISSUE THREAD

**Issue by bheimbu** [nick-youngblut/gtdb_to_taxdump#23]
Hi @nick-youngblut,

when I try to build the gtdb database using r207, I get:
```
gtdb_to_diamond.py -o gtdb gtdb_proteins_aa_reps_r207.tar.gz taxdump/names.dmp taxdump/nodes.dmp
2023-08-23 13:53:35,547 - Read nodes.dmp file: taxdump/nodes.dmp
2023-08-23 13:53:35,813 - File written: gtdb/nodes.dmp
2023-08-23 13:53:35,813 - Reading dumpfile: taxdump/names.dmp
2023-08-23 13:53:37,103 -   File written: gtdb/names.dmp
2023-08-23 13:53:37,103 -   No. of accession<=>taxID pairs: 398700
2023-08-23 13:53:37,104 - Extracting tarball: gtdb_proteins_aa_reps_r207.tar.gz
2023-08-23 13:53:37,104 -   Extracting to: gtdb_to_diamond_TMP
2023-08-23 14:13:05,126 -   No. of .faa(.gz) files: 65703
2023-08-23 14:13:05,150 - Creating accession2taxid table...
Traceback (most recent call last):
  File "/usr/users/bheimbu/mambaforge/bin/gtdb_to_diamond.py", line 79, in accession2taxid
    taxID = names_dmp[accession]
KeyError: 'GCA003697015.1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/users/bheimbu/mambaforge/bin/gtdb_to_diamond.py", line 146, in <module>
    main(args)
  File "/usr/users/bheimbu/mambaforge/bin/gtdb_to_diamond.py", line 135, in main
    accession2taxid(names_dmp, faa_files, args.outdir)
  File "/usr/users/bheimbu/mambaforge/bin/gtdb_to_diamond.py", line 82, in accession2taxid
    raise KeyError(msg.format(accession))
KeyError: 'Cannot find GCA003697015.1 accession in names.dmp'
```
Any help is highly appreciated,

Bastian

**Comment by nick-youngblut** [comment]
I've changed the keyerror to a warning, which should provide more info on whether there are many non-overlapping accessions between the tarball and dmp files, or if it is just `GCA003697015.1`. Run the command again and see how many warnings that you get.

**Comment by bheimbu** [comment]
After updating `gtdb_to_diamond.py` I get following error:
```
gtdb_to_diamond.py -o gtdb_vers207 gtdb_proteins_aa_reps_r207.tar.gz taxdump/names.dmp taxdump/nodes.dmp
2023-08-24 09:28:58,061 - Read nodes.dmp file: taxdump/nodes.dmp
2023-08-24 09:28:58,616 - File written: gtdb_vers207/nodes.dmp
2023-08-24 09:28:58,616 - Reading dumpfile: taxdump/names.dmp
2023-08-24 09:29:01,492 -   File written: gtdb_vers207/names.dmp
2023-08-24 09:29:01,492 -   No. of accession<=>taxID pairs: 398700
2023-08-24 09:29:01,493 - Extracting tarball: gtdb_proteins_aa_reps_r207.tar.gz
2023-08-24 09:29:01,493 -   Extracting to: gtdb_to_diamond_TMP
2023-08-24 10:06:43,630 -   No. of .faa(.gz) files: 65703
2023-08-24 10:06:43,675 - Creating accession2taxid table...
2023-08-24 10:06:43,676 - WARNING: Cannot find GCA003697015.1 accession in names.dmp
Traceback (most recent call last):
  File "/usr/users/bheimbu/mambaforge/bin/gtdb_to_diamond.py", line 146, in <module>
    main(args)
  File "/usr/users/bheimbu/mambaforge/bin/gtdb_to_diamond.py", line 135, in main
    accession2taxid(names_dmp, faa_files, args.outdir)
  File "/usr/users/bheimbu/mambaforge/bin/gtdb_to_diamond.py", line 84, in accession2taxid
    line = [acc_base, accession, str(taxID), '']
UnboundLocalError: local variable 'taxID' referenced before assignment
```

Cheers Bastian

**Comment by bheimbu** [comment]
Hi @nick-youngblut,

just to let you know. I've used ChatGPT to debug your code and it now runs probably without showing any warnings whatsoever. I changed your code as follows: 
```
#!/usr/bin/env python
# import
from __future__ import print_function
## batteries
import os
import shutil
import argparse
import logging
## package
from bin import __version__
import gtdb2td

# ... (other parts of the script remain unchanged)

# functions
def accession2taxid(names_dmp: dict, faa_files: dict, outdir: str) -> None:
    """ 
    Creating accession2taxid table.
    Params:
      names_dmp: dict of taxdump names.dmp file
      faa_files: dict of faa file paths and accessions 
      outdir: str output directory
    Returns:
      None (writes accession2taxid.tsv file)
    """
    outfile = os.path.join(outdir, 'accession2taxid.tsv')    
    logging.info('Creating accession2taxid table...')
    with open(outfile, 'w') as outF:
        header = ['accession', 'accession.version', 'taxid', 'gi']
        outF.write('\t'.join(header) + '\n')
        for accession,faa_file in faa_files.items():
            taxID = names_dmp.get(accession, "Not found")
            acc_base = os.path.splitext(accession)[0]
            line = [acc_base, accession, str(taxID), '']
            outF.write('\t'.join(line) + '\n')
    logging.info('  File written: {}'.format(outfile))
    
# ... (other parts of the script remain unchanged)

# script main
if __name__ == '__main__':
    args = parser.parse_args()
    main(args)
```
And the explanation given by ChatGPT:

> Certainly, here are the differences between the modified script I provided and the original script you posted:
>1) Access taxID Safely: In the accession2taxid function, I've modified the line where taxID is assigned using the names_dmp dictionary. Instead of directly accessing the dictionary with names_dmp[accession], I'm using the get() method to handle cases where the accession key is not found in the dictionary. This prevents the "UnboundLocalError" by assigning "Not found" as the value of taxID when the key is missing.
> 
>` taxID = names_dmp.get(accession, "Not found")`
> 
> 2) Handling Missing taxID: By using the get() method, the script will assign the string "Not found" to taxID when the accession is not found in the names_dmp dictionary. This prevents the script from raising an "UnboundLocalError" when trying to use taxID later in the code.

Cheers Bastian

**Comment by bheimbu** [comment]
I've changed your code (here is the adjusted [python script](https://github.com/nick-youngblut/gtdb_to_taxdump/files/12429016/gtdb_to_diamond.py.txt)) and it now runs. However, all accession numbers in `accession2taxid.tsv` are assigned to `Not found`, that is  `gtdb_to_diamond.py` gives me for every accession number, e.g. `Cannot find GCA001315985.1 accession in names.dmp`. So there must be wrong with the `nodes.dmp` file, right?
